# Generated by Django 5.2.5 on 2025-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(auto_created=True, default='2025-08-19'),
        ),
    ]
